[package]
name = "starknet"
version = "1.1.1"
edition = "2021"
authors = ["yogh333"]

[dependencies]
ledger_device_sdk = "1.8.2"
include_gif = "1.0.1"

[features]
default = []
pending_review_screen = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 'z' 
lto = true

[package.metadata.ledger]
curve = ["secp256k1"]
path = ["2645'"]
name = "Starknet"
flags = "0"

[package.metadata.ledger.nanos]
icon = "crab.gif"

[package.metadata.ledger.nanox]
icon = "starknet_small.gif"

[package.metadata.ledger.nanosplus]
icon = "starknet_small.gif"
