[package]
name = "nano-rapp-starknet"
version = "0.1.0"
edition = "2021"
authors = ["yogh333"]

[dependencies]
#nanos_sdk = { path = "../ledger-nanos-sdk/", features = ["speculos"] }
nanos_sdk = { path = "../ledger-nanos-sdk/" }  
nanos_ui = { path = "../ledger-nanos-ui/" }

[features]
default = [ "debug" ]
debug = ["nanos_sdk/speculos"]
device = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 'z' 
lto = true

[package.metadata.nanos]
curve = ["stark256"]
path = ["m/2645'/1195502025'/1148870696'/0'/0'/0"]
flags = "0"
icon = "crab.gif"
icon_small = "crab_14x14.gif"
