[package]
name = "starknet"
version = "0.1.1"
edition = "2021"
authors = ["grom"]

[dependencies]
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk.git" }
nanos_ui = { git = "https://github.com/LedgerHQ/ledger-nanos-ui.git" }

[features]
default = [ "speculos" ]
speculos = ["nanos_sdk/speculos", "nanos_ui/speculos"]
device = ["pending_review"]
pending_review = ["nanos_sdk/pending_review_screen"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 'z' 
lto = true

[package.metadata.ledger]
curve = ["secp256k1"]
path = ["m/2645'"]
name = "Starknet"
flags = "0"

[package.metadata.ledger.nanos]
icon = "crab.gif"

[package.metadata.ledger.nanox]
icon = "starknet_small.gif"

[package.metadata.ledger.nanosplus]
icon = "starknet_small.gif"
