[package]
name = "nano-rapp-starknet"
version = "0.1.0"
edition = "2021"
authors = ["yogh333"]

[dependencies]
#nanos_sdk = { path = "../ledger-nanos-sdk/", features = ["speculos"] }
nanos_sdk = { path = "../ledger-nanos-sdk/" }  
nanos_ui = { path = "../ledger-nanos-ui/" }
#crypto-bigint = { version = "0.4.9", default-features = false }

[features]
default = [ "debug" ]
debug = ["nanos_sdk/speculos", "nanos_ui/speculos"]
device = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 'z' 
lto = true

[package.metadata.nanos]
curve = ["secp256k1"]
path = ["m/2645'"]
flags = "0"
icon = "crab.gif"
icon_small = "starknet_small.gif"
name = "staRknet"