[package]
name = "starknet"
version = "1.0.0"
edition = "2021"
authors = ["yogh333"]

[dependencies]
ledger_device_sdk = "1.8.0"
include_gif = "1.0.1"

[features]
default = ["pending_review_screen"]
pending_review_screen = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 'z' 
lto = true

[package.metadata.ledger]
curve = ["secp256k1"]
path = ["2645'"]
name = "Starknet"
flags = "0"

[package.metadata.ledger.nanos]
icon = "crab.gif"

[package.metadata.ledger.nanox]
icon = "starknet_small.gif"

[package.metadata.ledger.nanosplus]
icon = "starknet_small.gif"

[patch.crates-io]
ledger_device_sdk = {path = "../ledger-device-rust-sdk/ledger_device_sdk"}
include_gif = {path = "../ledger-device-rust-sdk/include_gif"}
