[package]
name = "nano-rapp-starknet"
version = "0.1.0"
edition = "2021"
authors = ["yogh333"]

[dependencies]
nanos_sdk = { git = "https://github.com/LedgerHQ/ledger-nanos-sdk.git" }
nanos_ui = { git = "https://github.com/LedgerHQ/ledger-nanos-ui.git" }

[features]
default = [ "debug" ]
debug = ["nanos_sdk/speculos", "nanos_ui/speculos"]
device = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = 'z' 
lto = true

[package.metadata.nanos]
api_level = "1"
curve = ["secp256k1"]
path = ["m/2645'"]
flags = "0"
icon = "crab.gif"
icon_small = "starknet_small.gif"
name = "staRknet"