[unstable]
build-std = ["core"]
build-std-features = ["compiler-builtins-mem"]
profile-rustflags = true

[profile.release.package.compiler_builtins]
rustflags = ["-Zshare-generics=off"]

[build]
target = "nanosplus" 