name: Build through reusable workflow

# This workflow will build the app.
# It calls a reusable workflow developed by Ledger's internal developer team to build the application and upload the
# resulting binaries.

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  build_application:
    name: Build application using the reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: "compiled_app_binaries"
      builder: ledger-app-builder

  build_check_signature:
    name: Build binary used to check signture during the test
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-dev-tools:latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
      - name: Build
        run: |
          cargo build -p check-signature
      - name: Upload app binary
        uses: actions/upload-artifact@v4
        with:
          name: check-signature
          path: target/debug/check-signature
          if-no-files-found: error

  ragger_tests:
    name: Run ragger tests using the reusable workflow
    needs: build_application
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_ragger_tests.yml@v1
    with:
      download_app_binaries_artifact: "compiled_app_binaries"
      additional_app_binaries_artifact: "check-signature"
      additional_app_binaries_artifact_dir: "target/debug"
