name: Rust fmt

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs: 
      name: 
        description: 'Manually triggered'

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cargo fmt
        run: cargo fmt --all -- --check