name: Rust fmt

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
    inputs: 
      name: 
        description: 'Manually triggered'

env:
  CARGO_TERM_COLOR: always

jobs:
  rust_fmt:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder:latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cargo fmt
        working-directory: starknet
        run: cargo fmt --all -- --check
      
      - name: Cargo fmt
        working-directory: tools/apdu-generator
        run: cargo fmt --all -- --check
      
      - name: Cargo fmt
        working-directory: tools/check-signature
        run: cargo fmt --all -- --check

      - name: Cargo fmt
        working-directory: tools/tx-hash
        run: cargo fmt --all -- --check